version: "3.9"

services:
  mongodb:
    image: mongo
    container_name: developerapp-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo-data:/data/db
    networks:
      - develnet

  backend:
    build: ./backend
    container_name: developerapp-backend
    environment:
      MONGO_DB_USERNAME: user
      MONGO_DB_PWD: password
    depends_on:
      - mongodb
    ports:
      - "9000:9000"
    networks:
      - develnet

  frontend:
    build: ./frontend
    container_name: developerapp-frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"
    networks:
      - develnet

  mongo-express:
    image: mongo-express
    container_name: developerapp-mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: user
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
    depends_on:
      - mongodb
    networks:
      - develnet

networks:
  develnet:
    driver: bridge

volumes:
  mongo-data:
