services:
  mongodb:
    image: mongo
    container_name: developerapp-mongodb
    env_file:
      - .env
    volumes:
      - mongo-data:/data/db
    networks:
      - develnet

  backend:
    build: ./backend
    container_name: developerapp-backend

    env_file:
      - ./backend/.env

    secrets:
      - jwt_secret

    environment:
      JWT_SECRET_FILE: /run/secrets/jwt_secret

    depends_on:
      - mongodb

    ports:
      - "${BACKEND_PORT}:9000"

    networks:
      - develnet

  frontend:
    build: ./frontend
    container_name: developerapp-frontend
    env_file:
      - .env
    depends_on:
      - backend
    ports:
      - "3000:80"
    networks:
      - develnet

  nginx:
    image: nginx:alpine
    container_name: developerapp-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
    networks:
      - develnet

networks:
  develnet:
    driver: bridge

volumes:
  mongo-data:

secrets:
  jwt_secret:
    file: ./jwt_secret.txt
