version: "3.9"

services:
  mongodb:
    image: mongo
    container_name: developerapp-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - develnet

  backend:
    build: ./backend
    container_name: developerapp-backend
    environment:
      MONGO_DB_USERNAME: user
      MONGO_DB_PWD: password
    depends_on:
      - mongodb
    ports:
      - "9000:9000"
    networks:
      - develnet

  frontend:
    build: ./frontend
    container_name: developerapp-frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"
    networks:
      - develnet

networks:
  develnet:
    driver: bridge

volumes:
  mongo-data:
