name: Build Backend Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build root image
        run: docker build -t developerapp:latest .

      - name: Build backend image
        run: docker build ./backend -t developerapp-backend:latest

      - name: Build frontend image
        run: docker build ./frontend -t developerapp-frontend:latest

      - name: Install docker-compose
        run: sudo apt-get install docker-compose-plugin

      - name: Build compose stack
        run: docker compose build

