name: Build Backend Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build backend image
        run: docker build ./backend -t bisrat1/developerapp-backend:latest

      - name: Build frontend image
        run: docker build ./frontend -t bisrat1/developerapp-frontend:latest

      - name: Check docker compose version
        run: docker compose version

      - name: Build compose stack
        run: docker compose build

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Push backend image
        run: docker push bisrat1/developerapp-backend:latest

      - name: Push frontend image
        run: docker push bisrat1/developerapp-frontend:latest
